version: '3'
services:
  mysqldb:
    container_name: mysql
    image: mysql
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=@Dmi2020
      - MYSQL_DATABASE=main_bayan
      - MYSQL_PASSWORD=@Dmi2020
      - MYSQL_USER=admi
    volumes:
      - mysqlV:/var/lib/mysql
  backend-container:
    container_name: backend-container
    image: backend-image:2
    ports:
      - 8081:8081
    environment:
      - spring.datasource.url=jdbc:mysql://mysql:3306/main_bayan
  # frontend-container:
  #   image: frontend-image
  #   ports:
  #     - 9090:9090
  solr-container:
    container_name: solr-container
    image: solr:5.5.0
    ports:
      - 8983:8983
    volumes:
      - solrV:/var/solr
volumes:
  solrV:
  mysqlV:
