version: '3'
services:
  mysqldb:
    image: mysql
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=@Dmi2020
      - MYSQL_DATABASE=main_bayan
      - MYSQL_PASSWORD=@Dmi2020
      - MYSQL_USER=admi
    volumes:
      - mysqlV:/var/lib/mysql
  backend-container:
    image: backend-image
    ports:
      - 8080:8080
    environment:
      - spring.datasource.url=jdbc:mysql://-mysqldb:3306/main_bayan
  # frontend-container:
  #   image: frontend-image
  #   ports:
  #     - 9090:9090
  solr-container:
    image: solr:8.11.2
    ports:
      - 8983:8983
    volumes:
      - solrV:/var/solr
volumes:
  solrV:
  mysqlV:
